{
 "title": "OpenTemetry",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "traceId",
    "label": "traceId",
    "query": "21ade9b5c17ee968b13091ccab01e095"
   },
   { "name": "logLevel", "label": "logLevel", "query": "INFO, WARN, DEBUG, ERROR" }
  ]
 },
 "panels": [
  { "title": "Метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество запросов в секунду по каждому методу REST API ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_route =~\"/v1/.*\"}[$__rate_interval])) by (http_request_method, http_route, http_response_status_code)",
     "legendFormat": "{{http_request_method}} {{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Количество ошибок в логах приложения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_route =~\"/v1/.*\", http_response_status_code=~\"4..|5..\"}[$__rate_interval])) by (http_route, http_response_status_code)",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "99-й персентиль времени ответа HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(http_server_request_duration_seconds_bucket{http_route=~\"/v1/.*\"}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}} {{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  { "title": "Логи", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Все логи",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"}"
    }
   ]
  },
  {
   "title": "Поиск по logLevel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"}\r\n| severity_text=\"$logLevel\""
    }
   ]
  },
  {
   "title": "Поиск по traceId",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"}\r\n| trace_id=\"$traceId\""
    }
   ]
  },
  {
   "title": "Поиск по traceId и logLevel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"muffin-wallet\"}\r\n| severity_text=\"$logLevel\"\r\n| trace_id=\"$traceId\""
    }
   ]
  },
  { "title": "Трейсы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Трейсы",
   "type": "traces",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 43 },
   "targets": [
    { "query": "$traceId" }
   ]
  }
 ]
}