apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-log
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.logService.port }}
      targetPort: {{ .Values.logService.targetPort }}
