{
 "title": "muffin-wallet-logs",
 "time": { "from": "2026-02-03T01:30:29.227Z", "to": "2026-02-03T13:30:29.227Z" },
 "templating": {
  "list": [
   {
    "name": "traceId",
    "label": "traceId",
    "query": "6981dedaac9874fb5c53d5072d846be1"
   },
   { "name": "logLevel", "label": "logLevel", "query": "INFO, WARN, DEBUG, ERROR" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Все логи",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ job=\"muffin-wallet\" }",
     "legendFormat": "{ traceId = \"$traceId\" }"
    }
   ]
  },
  {
   "title": "Поиск по logLevel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ logLevel=\"$logLevel\" }"
    }
   ]
  },
  {
   "title": "Поиск по traceId",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ traceId=\"$traceId\", job=\"muffin-wallet\" }"
    }
   ]
  },
  {
   "title": "Поиск по logLevel и traceId",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ logLevel=\"$logLevel\", traceId=\"$traceId\" }"
    }
   ]
  },
  {
   "title": "Трассировка по traceId",
   "type": "traces",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "query": "$traceId" }
   ]
  }
 ]
}