{
 "title": "hw-prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов в секунду по каждому методу REST API вашего приложения.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri =~\"/v1/.*\"}[$__rate_interval])) by (method, uri, status)",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Количество ошибок в логах приложения.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri =~\"/v1/.*\", status=~\"4..|5..\"}[$__rate_interval])) by (uri, status)",
     "legendFormat": "{{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "99-й персентиль времени ответа HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{uri=~\"/v1/.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Количество активных соединений к базе данных PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"muffin_wallet\"}) by(datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}