apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}

    exporters:
      zipkin:
        endpoint: http://host.minikube.internal:9411/api/v2/spans

      prometheus:
        endpoint: "0.0.0.0:8889"

      otlphttp/loki:
        endpoint: http://host.minikube.internal:3100/otlp
        tls:
          insecure: true

      debug: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [zipkin]

        metrics:
          receivers: [otlp]
          exporters: [prometheus]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki]

      telemetry:
        logs:
          level: "info"